### ISSUE TITLE
spelling/capitalization consistency

### ISSUE THREAD

**Issue by sharkked** [sofycat/aseprite#4]
There's a couple file names here and there with incorrect spelling (pallet instead of palette, asesprite instead of aseprite) as well as directory capitalization that should be corrected for consistency's sake.
- [x] Rename all occurrences of pallet to palette (#5)
- [x] Correct the name of the repo to 'aseprite'
- [x] Update README.md links to 'aseprite' to match the renamed repo

**Comment by sofycat** [comment]
all done ty!
